# Generated by Django 5.2.4 on 2025-07-07 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('imdb_rating', models.FloatField(default=1, verbose_name='IMDB Rating')),
                ('kinopoisk_rating', models.FloatField(default=1)),
                ('image', models.CharField()),
                ('description', models.TextField()),
                ('release_year', models.IntegerField()),
                ('sources_list', models.JSONField(default=list, help_text="List of sources for the movie, e.g. ['source1', 'source2']")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='The Season Number')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('imdb_rating', models.FloatField(default=1, verbose_name='IMDB Rating')),
                ('kinopoisk_rating', models.FloatField(default=1)),
                ('image', models.CharField()),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('sources_list', models.JSONField(default=list, help_text="List of sources for the episode, e.g. ['source1', 'source2']")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='The Episode Number')),
                ('name', models.CharField(max_length=255)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch.season')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch.show'),
        ),
    ]
