# Generated by Django 5.2.4 on 2025-07-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.CharField(default=1, verbose_name='IMDB Rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='kinopoisk_rating',
            field=models.CharField(default=1),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='imdb_rating',
            field=models.CharField(default=1, verbose_name='IMDB Rating'),
        ),
        migrations.AlterField(
            model_name='show',
            name='kinopoisk_rating',
            field=models.CharField(default=1),
        ),
    ]
