# Generated by Django 5.2.4 on 2025-07-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_alter_movie_imdb_rating_alter_movie_kinopoisk_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_rating',
            field=models.CharField(default='1.0', verbose_name='IMDB Rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='kinopoisk_rating',
            field=models.CharField(default='1.0', verbose_name='Kinopoisk Rating'),
        ),
        migrations.AlterField(
            model_name='show',
            name='imdb_rating',
            field=models.CharField(default='1.0', verbose_name='IMDB Rating'),
        ),
        migrations.AlterField(
            model_name='show',
            name='kinopoisk_rating',
            field=models.CharField(default='1.0', verbose_name='Kinopoisk Rating'),
        ),
    ]
