# Generated by Django 5.2.4 on 2025-07-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_alter_movie_release_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='sources_list',
        ),
        migrations.AddField(
            model_name='show',
            name='sources_list',
            field=models.JSONField(default=list, help_text="List of sources for the episode, e.g. ['source1', 'source2']"),
        ),
    ]
